spring:
  application:
    name: authorizationService
  freemarker:
    suffix: .html
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: true
# Define the port where the UAA server would be running
server:
  port: 9999
  # Use different context-path to avoid session cookie overlapping
  context-path: /uaa
  use-forward-headers: true


ldap:
  contextSource:
    url: ldap://hqdemo1:389
    base: dc=cnnp,dc=com
    userDn: cn=root
    password: filenet
  contextConfiguration:
    userDnPatterns: uid={0}
    groupSearchBase:
    groupSearchFilter:
    userSearchBase:



# Define security
security:
  basic:
    enabled: false
  user:
    password: password
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**

  oauth2:
    resource:
      token-info-uri: /oauth/check_token
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----


