Aspring:
  application:
    name: productCatalogueService

# Define the port where the Widget Foundry server would be running
server:
  port: 8870


#eureka:
#    instance:
#        prefer-ip-address: true
#        lease-renewal-interval-in-seconds: 10
#        lease-expiration-duration-in-seconds: 10
#    client:
#        enabled: true
#        healthcheck:
#            enabled: true
#        registerWithEureka: true
#        fetchRegistry: true
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/